import type { ReactNode } from 'react';
import { Ruler, Trash2, X } from 'lucide-react';
import { FloorObject, getArea } from './types';

interface PropertiesPanelProps { selected: FloorObject | null; onUpdate: (patch: Partial<FloorObject>) => void; onDelete: () => void; onClear: () => void; }

export function PropertiesPanel({ selected, onUpdate, onDelete, onClear }: PropertiesPanelProps) {
  return <aside className="w-[260px] shrink-0 overflow-y-auto border-l border-slate-200 bg-white p-5 scrollbar-thin lg:w-[286px]">
    <div className="mb-7 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-400">Inspector</p><h2 className="mt-1 font-display text-lg font-bold text-slate-900">Properties</h2></div>{selected && <button onClick={onClear} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><X size={16} /></button>}</div>
    {selected ? <div className="animate-scale-in"><div className="mb-6 flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-white text-indigo-600 shadow-sm"><Ruler size={19} /></div><div><p className="text-xs font-semibold text-slate-800">{selected.label}</p><p className="text-[10px] uppercase tracking-wider text-slate-400">{selected.type}</p></div></div><div className="space-y-5"><Field label="Name"><input value={selected.label} onChange={(e) => onUpdate({ label: e.target.value })} className="input" /></Field><div><p className="mb-2 text-xs font-semibold text-slate-500">Dimensions <span className="font-normal text-slate-400">(cm)</span></p><div className="grid grid-cols-2 gap-2"><Field label="Width"><input type="number" value={selected.width} onChange={(e) => onUpdate({ width: Number(e.target.value) })} className="input" /></Field><Field label="Height"><input type="number" value={selected.height} onChange={(e) => onUpdate({ height: Number(e.target.value) })} className="input" /></Field></div></div><div><p className="mb-2 text-xs font-semibold text-slate-500">Position <span className="font-normal text-slate-400">(cm)</span></p><div className="grid grid-cols-2 gap-2"><Field label="X"><input type="number" value={Math.round(selected.x)} onChange={(e) => onUpdate({ x: Number(e.target.value) })} className="input" /></Field><Field label="Y"><input type="number" value={Math.round(selected.y)} onChange={(e) => onUpdate({ y: Number(e.target.value) })} className="input" /></Field></div></div><div className="rounded-xl border border-indigo-100 bg-indigo-50/60 p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-indigo-500">Calculated area</p><p className="mt-1 font-display text-2xl font-bold text-indigo-900">{getArea(selected).toFixed(2)} <span className="text-sm font-medium">m²</span></p></div><button onClick={onDelete} className="flex w-full items-center justify-center gap-2 rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm font-semibold text-red-600 transition hover:bg-red-100"><Trash2 size={16} /> Delete object</button></div></div> : <div className="flex flex-col items-center py-12 text-center"><div className="mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-50 text-slate-300"><Ruler size={25} /></div><p className="text-sm font-semibold text-slate-600">Nothing selected</p><p className="mt-2 max-w-[180px] text-xs leading-5 text-slate-400">Select an object on the canvas to inspect its properties.</p></div>}
    <style>{`.input{width:100%;border:1px solid #e2e8f0;border-radius:8px;padding:8px 10px;font-size:12px;color:#334155;background:#fff;outline:none;transition:border .2s,box-shadow .2s}.input:focus{border-color:#818cf8;box-shadow:0 0 0 3px #eef2ff}`}</style>
  </aside>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="mb-1 block text-[10px] font-medium text-slate-400">{label}</span>{children}</label>; }
